.MODEL SMALL  ;TINNY, LARGE, EXTRA LARGE
.STACK 100H   ;STACK MEMORY
.CODE

MAIN PROC
    MOV AH,1
    INT 21H ;EXECUTION
    MOV BL,AL ;BL CONTAIN THE VALUE OF AL REGISTER
    
    MOV AH,2
    MOV DL, BL
    INT 21H 
    
    
     MOV AH,4CH
     INT 21H
     MAIN ENDP
END MAIN